### ISSUE TITLE
shared.module.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Ace-Ggl/shop#4]
Ответ на ваш вопрос по поводу сервиса, который не синглетон

Есть два типа стандартных модулей Shared
https://next.angular.io/guide/sharing-ngmodules
и Core.

Первый для компонент, директив, пайпов, которые повторно используются и может подключаться к какому-либо другому модулю, компоненты которого нуждаются в шаред компонентах, директивах, пайпах.

Второй модуль предпочтительно только для сервисов. Он может подключаться только в AppModule
Чтобы он больше ниге не подключался, есть даже кусок кода
https://next.angular.io/guide/singleton-services#prevent-reimport-of-the-coremodule

**Comment by Ace-Ggl** [comment]
Спасибо, теперь буду знать
