### ISSUE TITLE
products.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [Ace-Ggl/shop#5]
Восновном для сервисов нет необходмости писать интерфейсы. Есть ряд сервисов, при написании которых, мы указываем, что они реализуют определенный интерфейс. Но это не нужно делать для всех сервисов. Пример таких сервисов может быть guard, strategy

**Comment by Ace-Ggl** [comment]
Наверное это привычка от C# везде передавать интерфейсы, чтобы они разрешались в объекты. Здесь другой Dependency Injection, которому это не нужно. Хорошо
